export const CATALOG_VERSION = 3;

export const CATEGORY_DEFS = [
  {
    name: 'Laptops',
    slug: 'laptops',
    description: 'Work, study, and creator laptops with clear specs.',
    sortOrder: 0,
  },
  {
    name: 'Gaming PCs',
    slug: 'gaming-pcs',
    description: 'Ready-to-play desktops, from mid-range to 4K.',
    sortOrder: 1,
  },
  {
    name: 'Monitors',
    slug: 'monitors',
    description: 'Office, design, and gaming screens.',
    sortOrder: 2,
  },
  {
    name: 'Keyboards',
    slug: 'keyboards',
    description: 'Mechanical and office keyboards.',
    sortOrder: 3,
  },
  {
    name: 'Mice',
    slug: 'mice',
    description: 'Wireless and gaming mice.',
    sortOrder: 4,
  },
  {
    name: 'Headphones',
    slug: 'headphones',
    description: 'Headsets for games, calls, and music.',
    sortOrder: 5,
  },
  {
    name: 'Components',
    slug: 'components',
    description: 'GPUs, storage, and memory upgrades.',
    sortOrder: 6,
  },
  {
    name: 'Accessories',
    slug: 'accessories',
    description: 'Hubs, stands, and desk extras.',
    sortOrder: 7,
  },
] as const;

export const BRAND_DEFS = [
  'Brynoxa',
  'ASUS',
  'MSI',
  'Razer',
  'Dell',
  'Logitech',
  'Samsung',
  'NVIDIA',
] as const;

export type CatalogProduct = {
  name: string;
  slug: string;
  sku: string;
  category: string;
  brand: string;
  price: number;
  compareAtPrice?: number;
  stock: number;
  isFeatured?: boolean;
  isCarousel?: boolean;
  shortDescription: string;
  description: string;
  specs: Record<string, string>;
  tags: string[];
  image: string;
};

export const PRODUCT_DEFS: CatalogProduct[] = [
  {
    name: 'Brynoxa Blade 15 Pro',
    slug: 'brynoxa-blade-15-pro',
    sku: 'BRX-LAP-001',
    category: 'laptops',
    brand: 'Brynoxa',
    price: 18990,
    compareAtPrice: 21990,
    stock: 24,
    isFeatured: true,
    isCarousel: true,
    shortDescription: '15.6" creator laptop — i7, 32 GB RAM, RTX 4060.',
    description:
      'A thin 15.6" QHD laptop for design, code, and everyday work. Intel Core i7, 32 GB RAM, 1 TB SSD, and RTX 4060 graphics. 165 Hz screen. Ships with a 6-month warranty.',
    specs: {
      Use: 'Creators & work',
      CPU: 'Intel Core i7',
      RAM: '32 GB DDR5',
      Storage: '1 TB NVMe SSD',
      GPU: 'NVIDIA RTX 4060',
      Display: '15.6" QHD 165 Hz',
    },
    tags: ['laptop', 'creator', 'portable', 'rtx'],
    image: 'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=1200&q=80',
  },
  {
    name: 'MSI Stealth 16 Studio',
    slug: 'msi-stealth-16-studio',
    sku: 'MSI-LAP-016',
    category: 'laptops',
    brand: 'MSI',
    price: 20990,
    stock: 15,
    isFeatured: true,
    isCarousel: true,
    shortDescription: '16" Mini-LED studio laptop — i9 and RTX 4070.',
    description:
      'MSI Stealth 16 for 3D and video. Mini-LED color, Intel Core i9, 32 GB RAM, and RTX 4070. Built for long edit sessions.',
    specs: {
      Use: 'Video & 3D',
      CPU: 'Intel Core i9',
      RAM: '32 GB DDR5',
      Storage: '1 TB NVMe SSD',
      GPU: 'NVIDIA RTX 4070',
      Display: '16" Mini-LED',
    },
    tags: ['laptop', 'msi', 'creator', 'studio'],
    image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=1200&q=80',
  },
  {
    name: 'ASUS TUF Gaming A15',
    slug: 'asus-tuf-gaming-a15',
    sku: 'ASUS-LAP-015',
    category: 'laptops',
    brand: 'ASUS',
    price: 12990,
    stock: 22,
    isFeatured: false,
    isCarousel: true,
    shortDescription: 'Durable 15" gaming laptop — Ryzen 7 and RTX 4050.',
    description:
      'ASUS TUF A15 for gaming and schoolwork. Ryzen 7, 16 GB RAM, 512 GB SSD, RTX 4050, and a 144 Hz screen. Tough chassis, fair price.',
    specs: {
      Use: 'Gaming & study',
      CPU: 'AMD Ryzen 7',
      RAM: '16 GB DDR5',
      Storage: '512 GB NVMe SSD',
      GPU: 'NVIDIA RTX 4050',
      Display: '15.6" FHD 144 Hz',
    },
    tags: ['laptop', 'asus', 'gaming', 'tuf'],
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=1200&q=80',
  },
  {
    name: 'Brynoxa Phantom Rogue',
    slug: 'brynoxa-phantom-rogue',
    sku: 'BRX-PC-001',
    category: 'gaming-pcs',
    brand: 'Brynoxa',
    price: 24990,
    compareAtPrice: 27990,
    stock: 12,
    isFeatured: true,
    isCarousel: true,
    shortDescription: 'Liquid-cooled tower for 4K gaming — Ryzen 7 and RTX 4070 Ti.',
    description:
      'Factory-built gaming PC with strong cooling and room to upgrade. Ryzen 7, 32 GB RAM, 2 TB SSD, RTX 4070 Ti, 850 W Gold PSU. Ready for ultra settings.',
    specs: {
      Use: '4K gaming',
      CPU: 'AMD Ryzen 7',
      RAM: '32 GB DDR5',
      Storage: '2 TB NVMe SSD',
      GPU: 'NVIDIA RTX 4070 Ti',
      PSU: '850 W Gold',
    },
    tags: ['gaming', 'desktop', 'rtx', '4k'],
    image: 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=1200&q=80',
  },
  {
    name: 'Brynoxa Pulse 1440',
    slug: 'brynoxa-pulse-1440',
    sku: 'BRX-PC-002',
    category: 'gaming-pcs',
    brand: 'Brynoxa',
    price: 14990,
    stock: 18,
    isFeatured: false,
    isCarousel: true,
    shortDescription: '1440p gaming PC — Ryzen 5 and RTX 4060.',
    description:
      'A quieter mid-tower for 1440p games and classwork. Ryzen 5, 16 GB RAM, 1 TB SSD, RTX 4060, 650 W PSU. Easy first desktop.',
    specs: {
      Use: '1440p gaming',
      CPU: 'AMD Ryzen 5',
      RAM: '16 GB DDR5',
      Storage: '1 TB NVMe SSD',
      GPU: 'NVIDIA RTX 4060',
      PSU: '650 W Bronze',
    },
    tags: ['gaming', 'desktop', '1440p'],
    image: 'https://images.unsplash.com/photo-1593640408182-31c70c8268f5?w=1200&q=80',
  },
  {
    name: 'Samsung Odyssey OLED G6 27"',
    slug: 'samsung-odyssey-oled-g6-27',
    sku: 'BRX-MON-001',
    category: 'monitors',
    brand: 'Samsung',
    price: 7990,
    compareAtPrice: 8990,
    stock: 40,
    isFeatured: true,
    isCarousel: true,
    shortDescription: '27" OLED QHD 240 Hz — fast response, thin bezels.',
    description:
      'Samsung 27" OLED for games and film. 2560×1440, 240 Hz, HDR, USB-C. One cable can power a laptop and carry video.',
    specs: {
      Use: 'Gaming & media',
      Size: '27"',
      Panel: 'OLED',
      Resolution: '2560 × 1440',
      Refresh: '240 Hz',
    },
    tags: ['monitor', 'oled', 'gaming', 'qhd'],
    image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=1200&q=80',
  },
  {
    name: 'ASUS ROG Swift PG32 4K',
    slug: 'asus-rog-swift-pg32-4k',
    sku: 'ASUS-MON-032',
    category: 'monitors',
    brand: 'ASUS',
    price: 12990,
    stock: 10,
    isFeatured: false,
    isCarousel: true,
    shortDescription: '32" 4K 144 Hz gaming monitor — HDMI 2.1.',
    description:
      'ASUS ROG 32" 4K for PC and console. 144 Hz, HDMI 2.1, HDR. Sharp text for work, smooth games at night.',
    specs: {
      Use: '4K gaming',
      Size: '32"',
      Panel: 'IPS',
      Resolution: '3840 × 2160',
      Refresh: '144 Hz',
      HDR: 'HDR1600',
    },
    tags: ['monitor', '4k', 'rog', 'gaming'],
    image: 'https://images.unsplash.com/photo-1616588589676-62b3bd4ff6d1?w=1200&q=80',
  },
  {
    name: 'Dell 24" S2425HS Office',
    slug: 'dell-24-s2425hs-office',
    sku: 'DELL-MON-024',
    category: 'monitors',
    brand: 'Dell',
    price: 1890,
    stock: 50,
    isFeatured: false,
    shortDescription: '24" Full HD office screen — comfort for long days.',
    description:
      'Dell 24" FHD for office and study. Thin bezels, tilt stand, HDMI and DisplayPort. Simple second screen.',
    specs: {
      Use: 'Office & study',
      Size: '24"',
      Panel: 'IPS',
      Resolution: '1920 × 1080',
      Refresh: '100 Hz',
    },
    tags: ['monitor', 'office', 'fhd', 'dell'],
    image: 'https://images.unsplash.com/photo-1586210579191-33b45e38dd2f?w=1200&q=80',
  },
  {
    name: 'Razer Strike 75 Keyboard',
    slug: 'razer-strike-75-keyboard',
    sku: 'BRX-KB-001',
    category: 'keyboards',
    brand: 'Razer',
    price: 1490,
    stock: 80,
    isFeatured: true,
    shortDescription: '75% mechanical board — hot-swap, wireless, RGB.',
    description:
      'Compact 75% layout with hot-swap tactile switches, aluminum frame, and 2.4 G / Bluetooth / USB. Per-key RGB.',
    specs: {
      Use: 'Gaming & typing',
      Layout: '75%',
      Switches: 'Hot-swap tactile',
      Connectivity: '2.4G / Bluetooth / USB',
    },
    tags: ['keyboard', 'mechanical', 'wireless', 'razer'],
    image: 'https://images.unsplash.com/photo-1618384887929-16ec33cad2b5?w=1200&q=80',
  },
  {
    name: 'Logitech MX Keys S',
    slug: 'logitech-mx-keys-s',
    sku: 'LOG-KB-002',
    category: 'keyboards',
    brand: 'Logitech',
    price: 1290,
    stock: 60,
    isFeatured: false,
    shortDescription: 'Quiet office keyboard — multi-device, backlit keys.',
    description:
      'Logitech MX Keys S for writing and office work. Quiet keys, backlight, and Easy-Switch for computer, tablet, and phone.',
    specs: {
      Use: 'Office',
      Layout: 'Full',
      Switches: 'Low-profile scissor',
      Connectivity: 'Bluetooth / USB logi bolt',
    },
    tags: ['keyboard', 'office', 'wireless', 'logitech'],
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=1200&q=80',
  },
  {
    name: 'Logitech Aero Pro Wireless',
    slug: 'logitech-aero-pro-wireless',
    sku: 'BRX-MS-001',
    category: 'mice',
    brand: 'Logitech',
    price: 990,
    stock: 120,
    isFeatured: false,
    isCarousel: true,
    shortDescription: '58 g wireless gaming mouse — 26K DPI, 80-hour battery.',
    description:
      'Light wireless mouse for competitive games. 26K DPI sensor, optical clicks, about 80 hours per charge.',
    specs: {
      Use: 'Competitive gaming',
      Sensor: '26K DPI',
      Weight: '58 g',
      Battery: '80 hours',
      Connectivity: '2.4G / USB',
    },
    tags: ['mouse', 'wireless', 'gaming', 'logitech'],
    image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=1200&q=80',
  },
  {
    name: 'Razer Basilisk V3',
    slug: 'razer-basilisk-v3',
    sku: 'RZR-MS-002',
    category: 'mice',
    brand: 'Razer',
    price: 790,
    stock: 90,
    isFeatured: false,
    shortDescription: 'Wired ergonomic mouse — 11 buttons, RGB scroll.',
    description:
      'Razer Basilisk V3 for long sessions. Shaped for the right hand, extra buttons for MMO and browser shortcuts.',
    specs: {
      Use: 'MMO & desktop',
      Sensor: '26K DPI',
      Weight: '101 g',
      Connectivity: 'USB wired',
      Buttons: '11',
    },
    tags: ['mouse', 'wired', 'gaming', 'razer'],
    image: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=1200&q=80',
  },
  {
    name: 'Razer Nova Surround Headset',
    slug: 'razer-nova-surround-headset',
    sku: 'BRX-HP-001',
    category: 'headphones',
    brand: 'Razer',
    price: 1790,
    stock: 55,
    isFeatured: true,
    shortDescription: '50 mm gaming headset — detachable mic, USB or 3.5 mm.',
    description:
      'Closed-back headset with 50 mm drivers, memory-foam pads, and a detachable boom mic. USB or 3.5 mm for PC and console.',
    specs: {
      Use: 'Games & voice',
      Drivers: '50 mm',
      Mic: 'Detachable boom',
      Connectivity: 'USB / 3.5 mm',
    },
    tags: ['headset', 'gaming', 'audio', 'razer'],
    image: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=1200&q=80',
  },
  {
    name: 'Logitech Zone Vibe 100',
    slug: 'logitech-zone-vibe-100',
    sku: 'LOG-HP-002',
    category: 'headphones',
    brand: 'Logitech',
    price: 890,
    stock: 70,
    isFeatured: false,
    shortDescription: 'Wireless call headset — light, 20-hour battery.',
    description:
      'Logitech Zone Vibe 100 for calls and music. Bluetooth, flip-to-mute mic, about 20 hours. Office and commute.',
    specs: {
      Use: 'Calls & music',
      Drivers: '40 mm',
      Mic: 'Flip-to-mute',
      Connectivity: 'Bluetooth',
      Battery: '20 hours',
    },
    tags: ['headset', 'office', 'wireless', 'logitech'],
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=1200&q=80',
  },
  {
    name: 'NVIDIA GeForce RTX 4080 16 GB',
    slug: 'nvidia-geforce-rtx-4080-16gb',
    sku: 'BRX-GPU-001',
    category: 'components',
    brand: 'NVIDIA',
    price: 11990,
    stock: 18,
    isFeatured: true,
    isCarousel: true,
    shortDescription: '16 GB graphics card for 4K games and 3D work.',
    description:
      'NVIDIA RTX 4080 16 GB GDDR6X. Ray tracing, DLSS, PCIe 4.0. Needs a strong PSU (about 320 W TGP). For a desktop upgrade, not a laptop.',
    specs: {
      Use: 'GPU upgrade',
      VRAM: '16 GB GDDR6X',
      Interface: 'PCIe 4.0',
      TGP: '320 W',
    },
    tags: ['gpu', 'rtx', 'component', 'nvidia'],
    image: 'https://images.unsplash.com/photo-1591488320449-011701bb6704?w=1200&q=80',
  },
  {
    name: 'Brynoxa 2 TB NVMe SSD',
    slug: 'brynoxa-2tb-nvme-ssd',
    sku: 'BRX-SSD-001',
    category: 'components',
    brand: 'Brynoxa',
    price: 1290,
    stock: 80,
    isFeatured: false,
    shortDescription: '2 TB Gen4 SSD — faster boot and game loads.',
    description:
      'Internal M.2 NVMe SSD, 2 TB. PCIe Gen4. Drop-in storage upgrade for a compatible laptop or desktop.',
    specs: {
      Use: 'Storage upgrade',
      Capacity: '2 TB',
      Interface: 'M.2 NVMe PCIe Gen4',
      Form: '2280',
    },
    tags: ['ssd', 'storage', 'nvme', 'component'],
    image: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=1200&q=80',
  },
  {
    name: 'Brynoxa 32 GB DDR5 Kit',
    slug: 'brynoxa-32gb-ddr5-kit',
    sku: 'BRX-RAM-001',
    category: 'components',
    brand: 'Brynoxa',
    price: 890,
    stock: 100,
    isFeatured: false,
    shortDescription: '2×16 GB DDR5-5600 — extra RAM for edits and games.',
    description:
      'Matched 32 GB DDR5 kit (2×16 GB) at 5600 MT/s. Check your motherboard QVL before buying.',
    specs: {
      Use: 'RAM upgrade',
      Capacity: '32 GB (2×16 GB)',
      Type: 'DDR5-5600',
      Voltage: '1.25 V',
    },
    tags: ['ram', 'ddr5', 'component'],
    image: 'https://images.unsplash.com/photo-1562976540-1502c2145186?w=1200&q=80',
  },
  {
    name: 'Brynoxa ChargeDock USB-C Hub',
    slug: 'brynoxa-chargedock-usb-c-hub',
    sku: 'BRX-ACC-001',
    category: 'accessories',
    brand: 'Brynoxa',
    price: 690,
    stock: 200,
    isFeatured: false,
    shortDescription: '8-in-1 USB-C hub — HDMI 4K, 100 W pass-through.',
    description:
      'Aluminum 8-in-1 hub: HDMI 4K60, USB-A/C, SD/TF, Ethernet, 100 W Power Delivery. One dongle for a laptop bag.',
    specs: {
      Use: 'Laptop docking',
      Ports: '8-in-1',
      Power: '100 W PD',
      Video: 'HDMI 4K60',
    },
    tags: ['hub', 'usb-c', 'accessory', 'hdmi'],
    image: 'https://images.unsplash.com/photo-1625842268584-8f3296236761?w=1200&q=80',
  },
  {
    name: 'Brynoxa Aluminum Laptop Stand',
    slug: 'brynoxa-aluminum-laptop-stand',
    sku: 'BRX-ACC-002',
    category: 'accessories',
    brand: 'Brynoxa',
    price: 290,
    stock: 150,
    isFeatured: false,
    shortDescription: 'Raised laptop stand — cooler, better posture.',
    description:
      'Folding aluminum stand lifts the screen to eye height and improves airflow. Fits 11–17" laptops.',
    specs: {
      Use: 'Desk setup',
      Material: 'Aluminum',
      Fit: '11–17" laptops',
      Foldable: 'Yes',
    },
    tags: ['stand', 'laptop', 'accessory', 'desk'],
    image: 'https://images.unsplash.com/photo-1484788984921-03950022c9ef?w=1200&q=80',
  },
  {
    name: 'Brynoxa Desk Cable Kit',
    slug: 'brynoxa-desk-cable-kit',
    sku: 'BRX-ACC-003',
    category: 'accessories',
    brand: 'Brynoxa',
    price: 190,
    stock: 180,
    isFeatured: false,
    shortDescription: 'HDMI, USB-C, and USB-A cables — 1.5 m, ready for COD orders.',
    description:
      'Three everyday cables in one pack: HDMI 2.0, USB-C charging, USB-A to USB-C. 1.5 m each. For monitors, phones, and hubs.',
    specs: {
      Use: 'Cables',
      Length: '1.5 m each',
      Includes: 'HDMI 2.0, USB-C, USB-A to C',
    },
    tags: ['cables', 'hdmi', 'usb-c', 'accessory'],
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=80',
  },
];
